name: Build and Test React Application

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm build

      - name: Test
        run: npm test

      - uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: build/ # or path/to/artifact
  
  deploy:
      permissions:
        contents: write
      needs: [ build_and_test ] # Wait before running "deploy" until "validate_code" and "run_tests" are done
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@master
          with:
            name: build-dir
            path: build/ # or path/to/artifact
        - name: Deploy website 🚀
          uses: linus-jansson/github-pages-deploy-action@v4
          with:
            folder: build/ # The folder that should be used in the deployment