name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm ci

      - name: Build and next export
        run: npm run export

      - uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: out/ # or path/to/artifact
  deploy:
    permissions:
      contents: write
    needs: [ build ] # Wait before running "deploy" until "validate_code" and "run_tests" are done
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: build-dir
          path: out/ # or path/to/artifact
      - name: Deploy website 🚀
        uses: linus-jansson/github-pages-deploy-action@v4
        with:
          folder: out/ # The folder that should be used in the deployment