name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checking out Repo
        uses: actions/checkout@v3

      - name: Setting up node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build and next export
        run: npm run export

      - uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: out/ # or path/to/artifact

      - name: Deploy website 🚀
        uses: linus-jansson/github-pages-deploy-action@v4
        with:
          folder: out/ # The folder that should be used in the deployment
